[JargonPlayer]

# If enabled, allows mpv lib to load config files from the folder that contains JargonPlayer.exe
# EnableMpvConfig = true

# If set, overrides default location to save screenshots. Note: folder must exist
# ScreenshotsFolder = c:\screenshots

# If enabled, player will automatically step to next frame after taking a screenshot.
# This allows rapid capture of frame sequences with ctrl+s
# AutoAdvanceAfterScreenshot = true

# File type for screenshots
# Must be a type supported by mpv: png, jpg, jpeg, webp, jxl, avif
# ScreenshotFiletype = jpg